In [1]:
print("hello pawan")

hello pawan

In [ ]:
# we can also use how and other functions

In [ ]:
# we can also use how and other functions

In [ ]:
# we can also use how and other functions

In [ ]:
import pandas as pd
import numpy as np

In [82]:
data_rows = [
    ['John Smith', 50000, 25],
    ['Jane Doe', 60000, 30],
    ['Bob Johnson', 55000, 28]
]

In [83]:
d=pd.DataFrame(data_rows,columns=['Name', 'Salary', 'Age'])

In [84]:
d

          Name  Salary  Age
0   John Smith   50000   25
1     Jane Doe   60000   30
2  Bob Johnson   55000   28

In [85]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['NYC', 'LA', 'Chicago']
}

In [86]:
v = pd.DataFrame(data)

In [87]:
v

      Name  Age     City
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago

In [88]:
v[['Name','Age']]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
v["exp"]=["3","2","4"]

In [90]:
# axis= 1  mean found from up
# axis=0 mean found from left
# use (inplace = true) to permanentky change

In [91]:
v.drop("Age", axis = 1  )

      Name     City exp
0    Alice      NYC   3
1      Bob       LA   2
2  Charlie  Chicago   4

In [92]:
v

      Name  Age     City exp
0    Alice   25      NYC   3
1      Bob   30       LA   2
2  Charlie   35  Chicago   4

In [93]:
v.loc[[0,1]][["Age","City"]]

   Age City
0   25  NYC
1   30   LA

In [94]:
v[(v["Age"] > 25) & (v["City"] == 'LA')]

  Name  Age City exp
1  Bob   30   LA   2

In [97]:
data = {
    'Name': ['Alice', 'Bob', None, 'David', 'Eve'],
    'Age': [25, np.nan, 35, 28, np.nan],
    'City': ['NYC', 'LA', np.nan, None, 'Boston']
}

In [98]:
c = pd.DataFrame(data)

In [99]:
c

    Name   Age    City
0  Alice  25.0     NYC
1    Bob   NaN      LA
2   None  35.0     NaN
3  David  28.0    None
4    Eve   NaN  Boston

In [101]:
c.isna().sum()

Name    1
Age     2
City    2
dtype: int64

In [102]:
c.isna()

    Name    Age   City
0  False  False  False
1  False   True  False
2   True  False   True
3  False  False   True
4  False   True  False

In [103]:
c.isna().any()

Name    True
Age     True
City    True
dtype: bool

In [ ]:
c.dropna()
# dropna mean chenk in which row is no null value

    Name   Age City
0  Alice  25.0  NYC

In [ ]:
c.dropna(thresh=2)
# thresh at lat 2 non null value

    Name   Age    City
0  Alice  25.0     NYC
1    Bob   NaN      LA
3  David  28.0    None
4    Eve   NaN  Boston

In [106]:
c.fillna(0)

    Name   Age    City
0  Alice  25.0     NYC
1    Bob   0.0      LA
2      0  35.0       0
3  David  28.0       0
4    Eve   0.0  Boston

In [110]:
valu = {"Name":2,"Age":3,"City":4}
c.fillna(valu)

    Name   Age    City
0  Alice  25.0     NYC
1    Bob   3.0      LA
2      2  35.0       4
3  David  28.0       4
4    Eve   3.0  Boston

In [132]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'City': ['NYC', 'LA', 'Chicago', 'Houston']
})

# DataFrame 2
df2 = pd.DataFrame({
    # 'ID': [3, 4, 5, 6],
    'Salary': [70000, 80000, 65000, 90000],
    'Experience': [5, 8, 3, 10]
})

In [115]:
pd.merge(df1,df2)

   ID     Name     City  Salary  Experience
0   3  Charlie  Chicago   70000           5
1   4    David  Houston   80000           8

In [117]:
pd.merge(df1,df2,on= 'ID',how ='inner')

   ID     Name     City  Salary  Experience
0   3  Charlie  Chicago   70000           5
1   4    David  Houston   80000           8

In [118]:
pd.merge(df1,df2,on= 'ID',how ='outer')

   ID     Name     City   Salary  Experience
0   1    Alice      NYC      NaN         NaN
1   2      Bob       LA      NaN         NaN
2   3  Charlie  Chicago  70000.0         5.0
3   4    David  Houston  80000.0         8.0
4   5      NaN      NaN  65000.0         3.0
5   6      NaN      NaN  90000.0        10.0

In [119]:
pd.merge(df1,df2,on= 'ID',how ='left')

   ID     Name     City   Salary  Experience
0   1    Alice      NYC      NaN         NaN
1   2      Bob       LA      NaN         NaN
2   3  Charlie  Chicago  70000.0         5.0
3   4    David  Houston  80000.0         8.0

In [120]:
pd.merge(df1,df2,on= 'ID',how ='right')

   ID     Name     City  Salary  Experience
0   3  Charlie  Chicago   70000           5
1   4    David  Houston   80000           8
2   5      NaN      NaN   65000           3
3   6      NaN      NaN   90000          10

In [ ]:
pd.concat([df1,df2])
# we can also use axis

   ID     Name     City   Salary  Experience
0   1    Alice      NYC      NaN         NaN
1   2      Bob       LA      NaN         NaN
2   3  Charlie  Chicago      NaN         NaN
3   4    David  Houston      NaN         NaN
0   3      NaN      NaN  70000.0         5.0
1   4      NaN      NaN  80000.0         8.0
2   5      NaN      NaN  65000.0         3.0
3   6      NaN      NaN  90000.0        10.0

In [124]:
# pd.concat([df1,df2],axis=1)

In [134]:
df1.join(df2)

   ID     Name     City  Salary  Experience
0   1    Alice      NYC   70000           5
1   2      Bob       LA   80000           8
2   3  Charlie  Chicago   65000           3
3   4    David  Houston   90000          10

In [133]:
df2.join(df1)

   Salary  Experience  ID     Name     City
0   70000           5   1    Alice      NYC
1   80000           8   2      Bob       LA
2   65000           3   3  Charlie  Chicago
3   90000          10   4    David  Houston

In [135]:
import os
os.getcwd

In [146]:
df3=({
    'Team': ['A', 'A', 'B', 'B'],
    'Points': [10, 20, 30, 40],
    'Assists': [5, 7, 8, 6]
})
m = pd.DataFrame(df3)
m

  Team  Points  Assists
0    A      10        5
1    A      20        7
2    B      30        8
3    B      40        6

In [147]:
cat = m.groupby('Team')
cat
for i, v in cat:
    print(i)
    print(v)

A
  Team  Points  Assists
0    A      10        5
1    A      20        7
B
  Team  Points  Assists
2    B      30        8
3    B      40        6

In [ ]:
cat = m.groupby('Team')['Points'].sum()
cat

Team
A    30
B    70
Name: Points, dtype: int64

In [ ]:
# you can add more near team
#

In [ ]:
cat['points'].mean()

In [ ]:
cat['point'].agg(['mean','min','max','median','sum','count','std'])